### ISSUE TITLE
Most of the examples can't be build

### ISSUE THREAD

**Issue by Godzil** [pimoroni/32blit-beta#6]
It's probably to be expected considering it's an early release, but some of the example can't be build as is:

- [x]  fire
 Complain about missing `engine` and `graphics` namespace (they don't exist in the 32blit source tree)
- [x] flight
 For similar reasons (there are more errors, but could be due to the namespace issue)
- [x] matrix-test
 Similar reasons again
- [x] platformer
 Similar reasons, also look for an `input` namespace
- [x] sprite-test
 Similar reasons
 - [x] logo
 Again same reasons
- [x] particles
 Same
- [x] tilemap_test
 Same
- [ ] racer
 This one is an oddball. It is at link time that error come. It miss the functions:
 * `update(unsigned int)`
 * `render(unsigned int)` 
 * `init()`

All the non mentioned one seems to compile.

**Comment by Gadgetoid** [comment]
Ooof, good catch. I'd only ported a couple of examples to the "new" API since it was still in flux and I didn't want to waste effort.

I've now ported everything to the "new" API, albeit `racer` is an empty file- I should probably put some sort of TODO in there- and `tilemap_test` is currently segfaulting for some reason.

**Comment by ali1234** [comment]
`flight` segfaults because spritesheet::generate_mimaps() is causing random memory corruption.

**Comment by Gadgetoid** [comment]
I just built `rotozoom` and it crashes on startup in Windows. It's possibly doing something a little untoward.
